### ISSUE TITLE
Apply fixed conversation flow mode to Chat Widget of MVP

### ISSUE THREAD

**Issue by turnerrainer** [buerokratt/byk-widget-mvp#11]
AS A Product Owner
I WANT chatbot conversations to be both text- and fixed conversation flow-based
SO THAT I could apply them both according to what's most suitable in given situation

### Acceptance Criteria

- [x] Chat Widget displays optional selections for End User to choose from
- [x] End User can press on the button of choice
- [x] When in fixed conversation flow mode, the End User can not send any text
- [x] Conversations can be either text- or fixed conversation flow-based depending on how they have been defined in the back-end (Rasa + Ruuter DSLs)

#### DSL

- [x] Define JSON schema for chats in conversation flow mode

#### GUI

- [ ] Apply buttons based on JSON input from the backend
- [ ] Button values must be translatable `i18n` values

**Comment by baha-a** [comment]
PR:
- https://github.com/buerokratt/byk-widget-mvp/pull/12

**Comment by turnerrainer** [comment]
Back-end finished by @baha-a
@bartekpospiech will take over the GUI part

**Comment by KlviG** [comment]
Done, exept GUI part, due to prio changes
